#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/sharding?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: com.example.shardingjdbc.entity

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds
      ds:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sharding?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
    sharding:
      tables:
        user:
          actualDataNodes: ds.user${1..2}
          tableStrategy:
            inline:
              shardingColumn: id
              algorithmExpression: user${id % 2 + 1}
          keyGenerator:
            type: SNOWFLAKE
            column: id


